spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://hvuchunwxvwjok:835399a06a9169d5dca163de6c7a783a25b6de82e75f2133b5330a105b8db97f@ec2-54-159-35-35.compute-1.amazonaws.com:5432/dcijnqa053saem&createDatabaseIfNotExist=true
  #    username: root
  #    password:
  jpa:
    #    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: "Europe/Istanbul"

springdoc:
  pathsToMatch:"/api.*"

app:
  jwtSecret: dummySeretKeyPutRealComplexSecretKeyHere
  jwtExpirationInMs: 3600000
  defaultSorting: "id:desc"

cors:
  allowedOrigins: '*'
