spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_demo_db?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
#    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: "Europe/Istanbul"

springdoc:
  pathsToMatch:"/api.*"

app:
  jwtSecret: dummySeretKeyPutRealComplexSecretKeyHere
  jwtExpirationInMs: 3600000
  defaultSorting: "id:desc"

cors:
  allowedOrigins: '*'
